workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app-store
        bundle_identifier: com.tripgenie.app
      xcode: latest
      node: v18
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Set up provisioning profiles
        script: |
          app-store-connect fetch-signing-files \
            $(xcode-project detect-bundle-id) \
            --type IOS_APP_STORE \
            --create
      - name: Build iOS
        script: |
          xcode-project use-profiles
          xcode-project build-ipa \
            --workspace "ios/tripgenie.xcworkspace" \
            --scheme "tripgenie"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
      app_store_connect:
        submit_build: true 