workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
    
        bundle_identifier: com.tripgenie.app
      xcode: latest
      node: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Install pods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild build-for-distribution \
            -workspace ios/tripgenie.xcworkspace \
            -scheme tripgenie \
            -configuration Release \
            -archivePath build/tripgenie.xcarchive \
            -allowProvisioningUpdates
    artifacts:
      - build/tripgenie.xcarchive
    publishing:
      email:
        recipients:
          - your-email@example.com 